pub(crate) mod about;
pub(crate) mod gameplay;
pub(crate) mod general;
pub(crate) mod graphics;
pub(crate) mod hotkeys;
pub(crate) mod layout;
pub(crate) mod plugins;
#[cfg(feature = "training-tracker")]
pub(crate) mod training_tracker;
pub(crate) mod translations;
